server:
  port: 3000
  tomcat:
    relaxed-query-chars: "[,],{,},|,<,>"
    relaxed-path-chars: "[,],{,},|,<,>"
  connection-timeout: 5000

spring:
  datasource:
    username: root
    password: yangyiming.com
    url: jdbc:mysql://localhost:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
